# Setup
title:               African Digital Humanities at KU
tagline:             'African Digital Humanities initiatives at the University of Kansas.'
description:         'This site brings together various African Digital Humanities initiatives at the University of Kansas, including Onitsha Market Literature, Digital Nollywood, the African DH Symposium'
url:                 https://africandh-ku.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James yeku
  url:               https://afs.ku.edu/james-yeku
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
